axis_linear: 1  # Left thumb stick vertical
scale_linear: 1.0
scale_linear_turbo: 2.5

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.4

enable_button: 6  # Left trigger button
enable_turbo_button: 7  # Right trigger button
