target_frame: base_link # Leave empty to output scan in the pointcloud frame
tolerance: 1.0
min_height: 0.2
max_height: 1.5

angle_min: -0.74 # -42.6*M_PI/180.0
angle_max: 0.74 # 42.6*M_PI/180.0
angle_increment: 0.005 # M_PI/360.0
scan_time: 0.3333
range_min: 0.45
range_max: 4.0
use_inf: true

# Concurrency level, affects number of pointclouds queued for processing and number of threads used
# 0 : Detect number of cores
# 1 : Single threaded
# 2->inf : Parallelism level
concurrency_level: 1