controller_frequency: 15.0
recovery_behaviour_enabled: False
# Prohibit in place rotation commands since the robot cannot rotate in place (double Ackerman motor steering)
clearing_rotation_allowed: False

TebLocalPlannerROS:
  odom_topic: odom
  map_frame: odom

  # Trajectory
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  max_samples: 500
  global_plan_overwrite_orientation: False
  allow_init_with_backwards_motion: True
  # max_global_plan_lookahead_dist: 2.5
  max_global_plan_lookahead_dist: 3.0
  global_plan_viapoint_sep: 0.2
  global_plan_prune_distance: 1
  exact_arc_length: False
  feasibility_check_no_poses: 5
  publish_feedback: False
  control_look_ahead_poses: 1
  prevent_look_ahead_poses_near_goal: 1

  # Robot
  max_vel_x: 0.6 # m/s
  max_vel_x_backwards: 0.6 # m/s
  max_vel_y: 0.0 # m/s
  max_vel_theta: 1.0 # rad/s
  acc_lim_x: 3.0 # m/s²
  acc_lim_theta: 0.35 # rad/s²
  max_steering_rate: 5.0 # No idea what unit this is, rad/s² ?

  # ********************** Carlike robot parameters ********************
  min_turning_radius: 0.60 # meters
  wheelbase: 0.25 # Wheelbase of our robot in meters
  cmd_angle_instead_rotvel: False # stage simulator takes the angle instead of the rotvel as input (twist message)
  # ********************************************************************

  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "line"
    # radius: 0.2 # for type "circular"
    line_start: [-0.13056, 0.0] # for type "line"
    line_end: [0.13056, 0.0] # for type "line"
    front_offset: 0.46 # for type "two_circles"
    front_radius: 0.2 # for type "two_circles"
    rear_offset: 0.46 # for type "two_circles"
    rear_radius: 0.2 # for type "two_circles"
    vertices: [
        [0.5, 0.32925],
        [0.5, -0.32925],
        [-0.5, -0.32925],
        [-0.5, 0.32925],
      ] # for type "polygon"

  # Goal Tolerance
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.175
  free_goal_vel: False

  # Obstacles
  min_obstacle_dist: 0.42925 # Half width of the robot (0.32925m) + safety margin (0.10m)
  # min_obstacle_dist: 0.10
  inflation_dist: 0.4
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 15

  dynamic_obstacle_inflation_dist: 0.4
  include_dynamic_obstacles: True

  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 3

  costmap_converter/CostmapToLinesDBSRANSAC:
    cluster_max_distance: 0.4
    cluster_min_pts: 2
    ransac_inlier_distance: 0.15
    ransac_min_inliers: 10
    ransac_no_iterations: 500
    # ransac_no_iterations: 1000
    ransac_remainig_outliers: 3
    ransac_convert_outlier_pts: True
    ransac_filter_remaining_outlier_pts: False
    convex_hull_min_pt_separation: 0.1

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 10.0
  weight_max_vel_theta: 20.0
  weight_acc_lim_x: 30.0
  weight_acc_lim_theta: 40.0
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 70.0
  weight_optimaltime: 30.0 # must be > 0
  weight_max_steering_rate: 15.0 # must be > 0
  # weight_optimaltime: 1 # must be > 0
  weight_shortest_path: 0
  weight_obstacle: 150.0
  # weight_obstacle: 300
  weight_inflation: 0.2
  # weight_inflation: 1
  weight_dynamic_obstacle: 100 # not in use yet
  weight_dynamic_obstacle_inflation: 0.2
  weight_viapoint: 5.0
  weight_adapt_factor: 2

  # Homotopy Class Planner
  enable_homotopy_class_planning: True
  enable_multithreading: True
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.95
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: True
  # delete_detours_backwards: False # modified
  delete_detours_backwards: True # default
  max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: False

  # Recovery
  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
