#! /usr/bin/env python3

from copy import deepcopy
from actionlib import SimpleActionClient
from rr100_trajectory_tracking import GoToGoalTracker
from rr100_rl_msgs.msg import GoToPoseAction, GoToPoseGoal
from geometry_msgs.msg import PoseStamped
import rospy
import argparse
import numpy as np
import tf2_ros
import tf2_geometry_msgs  

def prompt_float(prompt: str) -> float:
    valid = False
    
    while not valid:
        try:
            value_str: str = input(prompt)
            value: float = float(value_str)
            valid = True
        except ValueError as e:
            print(f"Value entered is not a valid float: {e}")
    return value

def prompt_goal():
    frame = input("Enter the frame of the goal: ")
    x: float = prompt_float("Enter the X coordinate of the goal: ")
    y: float = prompt_float("Enter the Y coordinate of the goal: ")

    goal = GoToPoseGoal()
    goal.goal.point.x = x
    goal.goal.point.y = y
    goal.goal.header.frame_id = frame

    return goal

if __name__ == "__main__":
    rospy.init_node("rl_goal_sender")
    parser = argparse.ArgumentParser()
    parser.add_argument("--movement-controller-topic", "-t", default="/rl_controller")
    parser.add_argument("--distance-file", "-f", default="./distance_file.txt")
    args = parser.parse_args()
    
    client = SimpleActionClient(args.movement_controller_topic, ActionSpec=GoToPoseAction)
    rospy.loginfo(f"Waiting for client at '{args.movement_controller_topic}'")
    client.wait_for_server()

    tf_buffer = tf2_ros.Buffer()
    tf_listener = tf2_ros.TransformListener(tf_buffer)

    with open(args.distance_file, "+a") as f:
        try:
            quit = False
            while not quit:
                user_input = input("Enter a command :\n- q/CTRL+D: Quit\n- goto: send a goal to the rl controller\n")
                user_input = user_input.lower()
                if user_input == "q":
                    quit = True
                    continue
                if user_input == "goto":
                    goal = prompt_goal()
                    
                    tracker = GoToGoalTracker(goal.goal, f, tf_buffer)
                    client.send_goal(goal, feedback_cb=tracker.feedback_cb, done_cb=tracker.done_cb)
                    client.wait_for_result()
                else:
                    print("Unknown command")
                    continue
        except EOFError as e:
            rospy.signal_shutdown("User pressed CRTL + D")
    print("Exiting...")