#! /usr/bin/env python3

from copy import deepcopy
from actionlib import SimpleActionClient
from rr100_trajectory_tracking import RLTracker
from rr100_rl_msgs.msg import GoToPoseAction, GoToPoseGoal
from geometry_msgs.msg import PoseStamped
import rospy
import argparse
import numpy as np
import tf2_ros
import tf2_geometry_msgs  


if __name__ == "__main__":
    rospy.init_node("rl_goal_sender")
    parser = argparse.ArgumentParser()
    parser.add_argument("--movement-controller-topic", "-t", default="/rl_controller")
    parser.add_argument("--file", "-f", default="./random_goals.csv")
    parser.add_argument("--n-goals", "-n", default=20, type=int, help="Number of random goals to send before quitting")
    parser.add_argument("--goal-frame", "-g", default="odom", type=str, help="Frame in which to send the random goals")
    parser.add_argument("--seed", "-s", default=10, type=int, help="Random seed")
    parser.add_argument("--comment", "-c", default=None, type=str, help="Extra comment to add to file")
    args = parser.parse_args()

    np.random.seed(args.seed)
    
    client = SimpleActionClient(args.movement_controller_topic, ActionSpec=GoToPoseAction)
    rospy.loginfo(f"Waiting for client at '{args.movement_controller_topic}'")
    client.wait_for_server()

    tf_buffer = tf2_ros.Buffer()
    tf_listener = tf2_ros.TransformListener(tf_buffer)

    with open(args.file, "+a") as f:
        try:
            for i in range(args.n_goals):
                if i == 12:
                    input("Press enter to continue...")
                x = np.random.uniform(-2, 2)
                y = np.random.uniform(-2, 2)

                goal = GoToPoseGoal()
                goal.goal.point.x = x
                goal.goal.point.y = y
                goal.goal.header.frame_id = args.goal_frame
                
                print(f"Sending goal {i+1}/{args.n_goals}: ({x:.2f}, {y:.2f}) in frame '{args.goal_frame}'")
                
                tracker = RLTracker(goal.goal, f, tf_buffer, comment=args.comment)
                client.send_goal(goal, feedback_cb=tracker._feedback_cb, done_cb=tracker._done_cb)
                client.wait_for_result()
        except KeyboardInterrupt as e:
            rospy.signal_shutdown("User pressed CRTL + C")
    print("Exiting...")